---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-workspace-{{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.terraform.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: terraform-workspace-{{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - watch
- apiGroups:
    - ""
  resources:
    - "secrets"
    - "serviceaccounts"
  verbs:
    - "get"
    - "list"
    - "create"
    - "update"
    - "delete"
    - "watch"
    - "delete"
- apiGroups:
    - "coordination.k8s.io"
  resources:
    - "leases"
  verbs:
    - "get"
    - "create"
    - "update"
    - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: terraform-workspace-{{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: terraform-workspace-{{ include "app.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: terraform-workspace-{{ include "app.fullname" . }}
    namespace: {{ .Release.Namespace }}
