---
apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-workspace-{{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  name: {{ include "app.fullname" . }}
