---
apiVersion: terraform.frame.io/v1alpha1
kind: Workspace
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  serviceAccountName: terraform-workspace-{{ include "app.fullname" . }}
  approval: true
  module:
    source: git::https://github.com/terraform-aws-modules/terraform-aws-sqs.git
  variables:
    configMapName: terraform-workspace-{{ include "app.fullname" . }}
